### ISSUE TITLE
distribution validator slashes don't work in cybercli

### ISSUE THREAD

**Issue by SaveTheAles** [cybercongress/cyberd#237]
`docker exec -ti cyberd cyberdcli query distr slashes cybervaloper1jst67u54vquzvun3dawpmpwyx5ar8mayeyhlt9 1 200000`

logs:

```bash
panic: json: cannot unmarshal array into Go value of type map[string]json.RawMessage

goroutine 1 [running]:
github.com/tendermint/go-amino.(*Codec).MustUnmarshalJSON(0xc000175260, 0xc000038b18, 0x2, 0x3, 0xcf8620, 0xc00003f020)
	/root/go/pkg/mod/github.com/tendermint/go-amino@v0.14.1/amino.go:445 +0x8a
github.com/cosmos/cosmos-sdk/x/distribution/client/cli.GetCmdQueryValidatorSlashes.func1(0xc0007ced80, 0xc000939b30, 0x3, 0x3, 0x0, 0x0)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.30.0/x/distribution/client/cli/query.go:147 +0x52a
github.com/spf13/cobra.(*Command).execute(0xc0007ced80, 0xc000939a70, 0x3, 0x3, 0xc0007ced80, 0xc000939a70)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:698 +0x47a
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001b58c0, 0x24, 0xc0000a329c, 0xe23742)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:783 +0x2dc
github.com/spf13/cobra.(*Command).Execute(0xc0001b58c0, 0x1, 0xc0000a6c40)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:736 +0x2b
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0001b58c0, 0xf7b9c8, 0x3, 0xc0000a32b0)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.29.1/libs/cli/setup.go:89 +0x4e
main.main()
	/sources/cli/main.go:71 +0x4dd
```

**Comment by xhipster** [comment]
slashes => slashing ?

**Comment by hleb-albau** [comment]
Fixed in the last cosmos update. Now returns: 
```
Validator Slash Events:
```
