### ISSUE TITLE
Can not explore existing account if it have not any outgoing transactions

### ISSUE THREAD

**Issue by SaveTheAles** [cybercongress/cyberd#238]
`docker exec cyberd cyberdcli query account cyber18pyqwgl6vse5485vuqedr2sd7uuzcy6c8g4dp7`

looking for account info, but

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa893bf]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/auth.BaseAccount.String(0xc0009250a0, 0x14, 0x14, 0xc00093f640, 0x1, 0x1, 0x0, 0x0, 0x204e4, 0x0, ...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.30.0/x/auth/account.go:91 +0x3f
github.com/cosmos/cosmos-sdk/client/context.CLIContext.PrintOutput(0xc000171ea0, 0xc000a22c00, 0x10491c0, 0xc0009e1bc0, 0x1034260, 0xc0000a4008, 0xe0c442, 0x4, 0x0, 0xe1b6ab, ...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.30.0/client/context/context.go:266 +0x253
github.com/cosmos/cosmos-sdk/x/auth/client/cli.GetAccountCmd.func1(0xc0009fa6c0, 0xc000a22360, 0x1, 0x1, 0x0, 0x0)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.30.0/x/auth/client/cli/account.go:38 +0x320
github.com/spf13/cobra.(*Command).execute(0xc0009fa6c0, 0xc000a22330, 0x1, 0x1, 0xc0009fa6c0, 0xc000a22330)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:698 +0x47a
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001ad680, 0x24, 0xc000a1c2ac, 0xe23742)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:783 +0x2dc
github.com/spf13/cobra.(*Command).Execute(0xc0001ad680, 0x1, 0xc00000ea10)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:736 +0x2b
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0001ad680, 0xf7b9c8, 0x3, 0xc000a1c2c0)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.29.1/libs/cli/setup.go:89 +0x4e
main.main()
	/sources/cli/main.go:71 +0x4dd
```

**Comment by hleb-albau** [comment]
Fixed in the last update. Now, cli return next output for such addresses:
```
ERROR: No account with address cyber18nqsthf0flyahlwwtsjwdne34jf7n4yhwcrdyz was found in the state.
Are you sure there has been a transaction involving it?
```
